### ISSUE TITLE
openlawdc?

### ISSUE THREAD

**Issue by tmcw** [dclegalhackers/ideas#1]
should we merge somehow? https://github.com/openlawdc

**Comment by adelevie** [comment]
I'm fine with it. Are you proposing just moving the repos over? Or something else/more?

Thoughts, @rebeccawilliams?

**Comment by rebeccawilliams** [comment]
Fine with it too!

**Comment by adelevie** [comment]
@tmcw, how about we grant you membership to the GitHub org, and you can merge as you see fit?

**Comment by tmcw** [comment]
on second thought, let's see where things go first!
